import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


type LayoutProps = {
   children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "chat-twilio-ai",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<LayoutProps>) {
   return (
      <html lang="en">
         <body className={inter.className}>{children}</body>
      </html>
   );
}
